anthropic:
  ANTHROPIC_KEY: ''
anthropic_vertex:
  PROJECT_ID: ''
  REGION: ''
azure:
  AZURE_OPENAI_API_KEY: ''
  AZURE_OPENAI_ENDPOINT: ''
  OPENAI_API_VERSION: ''
google:
  GOOGLE_API_KEY: ''
openai:
  OPENAI_API_BASE: ''
  OPENAI_API_KEY: ''
  OPENAI_ORGANIZATION: ''
oracle:
  COMPARTMENT_ID: ''
  SERVICE_ENDPOINT: ''
